# Generated by Django 5.2.8 on 2026-04-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placecoordinates',
            name='address',
            field=models.CharField(max_length=255, unique=True, verbose_name='кэшированный адрес'),
        ),
        migrations.AlterField(
            model_name='placecoordinates',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='placecoordinates',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='долгота'),
        ),
        migrations.AlterField(
            model_name='placecoordinates',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата обновления'),
        ),
    ]
