# Generated by Django 5.2.8 on 2025-11-17 16:17

from django.db import migrations


def add_product_price(apps, schema_editor):
    OrderProduct = apps.get_model("foodcartapp", "OrderProduct")
    for item in OrderProduct.objects.filter(product_price__isnull=True):
        item.product_price = item.product.price
        item.save()


class Migration(migrations.Migration):
    dependencies = [
        ("foodcartapp", "0039_orderproduct_product_price"),
    ]

    operations = [
        migrations.RunPython(add_product_price),
    ]
