# Generated by Django 5.2.8 on 2025-12-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_alter_orderproduct_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('manager', 'В обработке'), ('restaurant', 'Собираем заказ'), ('courier', 'Заказ в пути'), ('client', 'Доставлено')], default='client', max_length=50),
        ),
    ]
