# Generated by Django 5.2.8 on 2025-12-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=100, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('manager', 'В обработке'), ('restaurant', 'Собираем заказ'), ('courier', 'Заказ в пути'), ('client', 'Доставлено')], default='manager', max_length=50),
        ),
    ]
