# Generated by Django 5.2.8 on 2025-12-28 11:48

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_confirmed_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Контактный телефон', max_length=128, region=None, verbose_name='Номер телефона'),
        ),
    ]
