# Generated by Django 5.2.8 on 2026-01-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_alter_order_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('manager', 'В обработке'), ('restaurant', 'Собираем заказ'), ('courier', 'Заказ в пути'), ('client', 'Доставлено')], default='Не обработан', max_length=50),
        ),
    ]
